################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
build/debug/project \
build/debug/project/autogen \
build/debug/sdk/app/bluetooth/common/in_place_ota_dfu \
build/debug/sdk/app/common/util/app_log \
build/debug/sdk/app/common/util/app_timer \
build/debug/sdk/hardware/board/src \
build/debug/sdk/hardware/driver/configuration_over_swo/src \
build/debug/sdk/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
build/debug/sdk/platform/Device/SiliconLabs/EFR32BG13P/Source \
build/debug/sdk/platform/bootloader/api \
build/debug/sdk/platform/bootloader/app_properties \
build/debug/sdk/platform/common/src \
build/debug/sdk/platform/common/toolchain/src \
build/debug/sdk/platform/driver/debug/src \
build/debug/sdk/platform/driver/i2cspm/src \
build/debug/sdk/platform/emdrv/dmadrv/src \
build/debug/sdk/platform/emdrv/spidrv/src \
build/debug/sdk/platform/emlib/src \
build/debug/sdk/platform/radio/rail_lib/plugin/pa-conversions \
build/debug/sdk/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
build/debug/sdk/platform/radio/rail_lib/plugin/rail_util_sequencer \
build/debug/sdk/platform/security/sl_component/sl_mbedtls_support/src \
build/debug/sdk/platform/security/sl_component/sl_protocol_crypto/src \
build/debug/sdk/platform/security/sl_component/sl_psa_driver/src \
build/debug/sdk/platform/service/device_init/src \
build/debug/sdk/platform/service/iostream/src \
build/debug/sdk/platform/service/power_manager/src \
build/debug/sdk/platform/service/sleeptimer/src \
build/debug/sdk/platform/service/system/src \
build/debug/sdk/platform/service/udelay/src \
build/debug/sdk/protocol/bluetooth/bgcommon/src \
build/debug/sdk/protocol/bluetooth/src \
build/debug/sdk/util/silicon_labs/silabs_core/memory_manager \
build/debug/sdk/util/third_party/mbedtls/library \
gecko_sdk_4.4.4/app/bluetooth/common/in_place_ota_dfu \
gecko_sdk_4.4.4/app/common/util/app_log \
gecko_sdk_4.4.4/app/common/util/app_timer \
gecko_sdk_4.4.4/hardware/board/src \
gecko_sdk_4.4.4/hardware/driver/configuration_over_swo/src \
gecko_sdk_4.4.4/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
gecko_sdk_4.4.4/platform/Device/SiliconLabs/EFR32BG13P/Source \
gecko_sdk_4.4.4/platform/bootloader/api \
gecko_sdk_4.4.4/platform/bootloader/app_properties \
gecko_sdk_4.4.4/platform/common/src \
gecko_sdk_4.4.4/platform/common/toolchain/src \
gecko_sdk_4.4.4/platform/driver/debug/src \
gecko_sdk_4.4.4/platform/driver/i2cspm/src \
gecko_sdk_4.4.4/platform/emdrv/dmadrv/src \
gecko_sdk_4.4.4/platform/emdrv/spidrv/src \
gecko_sdk_4.4.4/platform/emlib/src \
gecko_sdk_4.4.4/platform/radio/rail_lib/plugin/pa-conversions \
gecko_sdk_4.4.4/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
gecko_sdk_4.4.4/platform/radio/rail_lib/plugin/rail_util_sequencer \
gecko_sdk_4.4.4/platform/security/sl_component/sl_mbedtls_support/src \
gecko_sdk_4.4.4/platform/security/sl_component/sl_protocol_crypto/src \
gecko_sdk_4.4.4/platform/security/sl_component/sl_psa_driver/src \
gecko_sdk_4.4.4/platform/service/device_init/src \
gecko_sdk_4.4.4/platform/service/iostream/src \
gecko_sdk_4.4.4/platform/service/power_manager/src \
gecko_sdk_4.4.4/platform/service/sleeptimer/src \
gecko_sdk_4.4.4/platform/service/system/src \
gecko_sdk_4.4.4/platform/service/udelay/src \
gecko_sdk_4.4.4/protocol/bluetooth/bgcommon/src \
gecko_sdk_4.4.4/protocol/bluetooth/lib/EFR32XG13/GCC \
gecko_sdk_4.4.4/protocol/bluetooth/src \
gecko_sdk_4.4.4/util/silicon_labs/silabs_core/memory_manager \
gecko_sdk_4.4.4/util/third_party/mbedtls/library \
src \
src/Fonts \
src/GUI \
src/e-ink \

