/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_human_interface_device_0       14
#define gattdb_protocol_mode                  16
#define gattdb_report                         18
#define gattdb_report_reference               20
#define gattdb_report_map                     22
#define gattdb_external_report_reference      23
#define gattdb_boot_keyboard_input_report     25
#define gattdb_boot_keyboard_output_report    28
#define gattdb_boot_mouse_input_report        30
#define gattdb_hid_information                33
#define gattdb_hid_control_point              35
#define gattdb_device_information_0           36
#define gattdb_manufacturer_name_string       38
#define gattdb_model_number_string            40
#define gattdb_serial_number_string           42
#define gattdb_hardware_revision_string       44
#define gattdb_firmware_revision_string       46
#define gattdb_software_revision_string       48
#define gattdb_system_id                      50
#define gattdb_ieee_11073_20601_regulatory_certification_data_list 52
#define gattdb_pnp_id                         54
#define gattdb_scan_parameters_0              55
#define gattdb_scan_interval_window           57
#define gattdb_scan_refresh                   59
#define gattdb_battery_service_0              61
#define gattdb_battery_level                  63
#define gattdb_characteristic_presentation_format 64
#define gattdb_ota                            65
#define gattdb_ota_control                    67


#endif // __GATT_DB_H
