/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_serial_number_string_0         26
#define gattdb_software_revision_string_0     28
#define gattdb_pnp_id_0                       30
#define gattdb_battery_service_0              31
#define gattdb_battery_level                  33
#define gattdb_characteristic_presentation_format 34
#define gattdb_human_interface_device_0       35
#define gattdb_protocol_mode                  37
#define gattdb_report                         39
#define gattdb_report_reference               41
#define gattdb_report_map                     43
#define gattdb_external_report_reference      44
#define gattdb_hid_information                46
#define gattdb_hid_control_point              48
#define gattdb_ota                            49
#define gattdb_ota_control                    51


#endif // __GATT_DB_H
